### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.tabos.twofun#1]
TwoFun seems to have no icon.

**Comment by bilelmoussaoui** [comment]
Because the desktop file doesn't have an icon entry https://gitlab.com/tabos/twofun/blob/master/data/org.tabos.Twofun.desktop.in#L1 nor it ships an icon at all.
I think we need a new test on Flathub to catch those kind of situations as the desktop file passes desktop-file-validate, I don't know if we have something that checks if there's an Icon attribute on the desktop file.

**Comment by janbrummer** [comment]
Indeed, i'm not an artist and missed this. Will try to fix it with an intermediate icon.

**Comment by bilelmoussaoui** [comment]
I think you could ask the GNOME design team and see if someone wants to make a fancy icon for your app :)

**Comment by janbrummer** [comment]
Fixed with latest commit (missed the closes line..)
